services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    profiles:
      - prod
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/html:/var/www/html
    env_file:
      - ./.env
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    profiles:
      - prod
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    env_file:
      - ./.env
    command: certbot certonly --standalone -d ${DOMAIN}
