# Generated by Django 5.0 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.TextField(
                blank=False,
                default="",
                help_text="Comma-separated list of technologies.",
            ),
        ),
    ]
