# Generated by Django 5.0 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_publish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["display_order", "-id"]},
        ),
        migrations.CreateModel(
            name="PortfolioContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featured", models.BooleanField(default=True)),
                ("intro", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first.",
            ),
        ),
    ]
