# Generated by Django 5.0 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_publish"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["display_order", "-id"]},
        ),
        migrations.AddField(
            model_name="project",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Lower numbers appear first.",
            ),
        ),
        migrations.RenameField(
            model_name="project",
            old_name="description",
            new_name="problem",
        ),
        migrations.AlterField(
            model_name="project",
            name="problem",
            field=models.TextField(blank=False),
        ),
        migrations.AddField(
            model_name="project",
            name="competencies_demonstrated",
            field=models.TextField(blank=False, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="solution",
            field=models.TextField(blank=False, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_choices",
            field=models.TextField(blank=False, default=""),
        ),
    ]
