# Generated by Django 5.2.12 on 2026-05-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_project_options_project_display_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='publish',
            new_name='public',
        ),
    ]
