# Generated by Django 5.0 on 2026-05-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_portfoliocontext_project_display_order"),
        ("portfolio", "0004_project_case_study_fields"),
        ("portfolio", "0004_project_tech_stack"),
        ("portfolio", "0006_project_featured"),
    ]

    operations = []
