# Generated by Django 5.2.12 on 2026-05-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_merge_portfolio_project_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                upload_to="portfolio/resources/upload/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail_caption",
            field=models.TextField(blank=True),
        ),
    ]
