# Generated by Django 5.2.12 on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_project_thumbnail_project_thumbnail_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="card_icon",
            field=models.ImageField(
                blank=True,
                upload_to="portfolio/resources/upload/icons/projects/",
            ),
        ),
    ]
