# Generated by Django 5.2.12 on 2026-05-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_project_card_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ("prototype", "Prototype"),
                    ("beta", "Beta"),
                    ("stable", "Stable"),
                ],
                default="stable",
                max_length=20,
            ),
        ),
    ]
