# Generated by Django 5.2.12 on 2026-05-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpostsnippet_side_scroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostparagraph',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpostsnippet',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='blog.blogpostparagraph'),
        ),
    ]
