# Generated by Django 5.2.8 on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blogpost_as_markdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featured", models.BooleanField(default=True)),
                ("intro", models.TextField()),
            ],
        ),
    ]
