# Generated by Django 5.2.12 on 2026-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_blogcontext"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpostsnippet",
            name="paragraph",
        ),
        migrations.DeleteModel(
            name="BlogPostParagraph",
        ),
        migrations.DeleteModel(
            name="BlogPostSnippet",
        ),
    ]
