# Generated by Django 5.0 on 2024-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(help_text='NOTE: Add a blank space to empty lines to maintain the line break.'),
        ),
    ]
