# Generated by Django 5.0 on 2026-05-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_about_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("featured", models.BooleanField(default=True)),
                ("headline", models.TextField(blank=False)),
                ("intro", models.TextField(blank=False)),
                (
                    "skills",
                    models.TextField(
                        blank=False,
                        help_text="Comma-separated list of skills.",
                    ),
                ),
            ],
        ),
    ]
