# Generated by Django 5.2.12 on 2026-05-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_about_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='intro',
        ),
        migrations.AddField(
            model_name='about',
            name='background',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='focus_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='focus_list',
            field=models.TextField(default='', help_text='List each entry with "- " on a new line.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='mindset_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='mindset_list',
            field=models.TextField(default='', help_text='List each entry with "- " on a new line.'),
            preserve_default=False,
        ),
    ]
